# ----
# Site

title: GraphJS Documentation
description: GraphJS Documentation
url: https://github.com/codezilla2018/GraphJS
google_analytics_key:
permalink: pretty

# -----
# Build

timezone: Etc/UTC

collections:
  documentation:
    title: Documentation
    position: 1
  api:
    title: API
    position: 2
  chart:
    title: Chart
    position: 3
  axis:
    title: Axis
    position: 4
  chart_data:
    title: Data
    position: 5
  grid:
    title: Grid
    position: 6
  region:
    title: Region
    position: 7
  interaction:
    title: Interaction
    position: 8
  legend:
    title: Legend
    position: 9
  tooltip:
    title: Tooltip
    position: 10
  chart_options:
    title: Chart Options
    position: 11
  line_chart_options:
    title: Line Chart Options
    position: 12
  pie_chart_options:
    title: Pie Chart Options
    position: 13
  transform:
    title: Transform
    position: 14
  style:
    title: Style
    position: 15

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENSE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      type: "documentation"
    values:
      _hide_content: true
  -
    scope:
      type: "api"
    values:
      _hide_content: true
  -
    scope:
      type: "chart"
    values:
      _hide_content: true
  -
    scope:
      type: "axis"
    values:
      _hide_content: true
  -
    scope:
      type: "chart_data"
    values:
      _hide_content: true
  -
    scope:
      type: "grid"
    values:
      _hide_content: true
  -
    scope:
      type: "region"
    values:
      _hide_content: true
  -
    scope:
      type: "interaction"
    values:
      _hide_content: true
  -
    scope:
      type: "legend"
    values:
      _hide_content: true
  -
    scope:
      type: "tooltip"
    values:
      _hide_content: true
  -
    scope:
      type: "chart_options"
    values:
      _hide_content: true
  -
    scope:
      type: "line_chart_options"
    values:
      _hide_content: true
  -
    scope:
      type: "pie_chart_options"
    values:
      _hide_content: true
  -
    scope:
      type: "transform"
    values:
      _hide_content: true
  -
    scope:
      type: "style"
    values:
      _hide_content: true


# -----------
# CloudCannon

types:
  - get
  - put
  - delete
  - post

languages:
  bash: Bash
  c: C
  css: CSS
  html: HTML
  java: Java
  javascript: JavaScript
  json: JSON
  php: PHP
  python: Python
  ruby: Ruby

_options:
  content_markdown:
    format: p h4 h5 h6
    bold: true
    italic: true
    link: true
    bulletedlist: true
    numberedlist: true
    image: true
    table: true
    styles: /css/editor.css
